config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from config import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('post/', include('post.urls', namespace='post')),
    
    path('', views.home_view, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post import views

app_name = 'post'

urlpatterns = [
    path('', views.list_post_view, name='list-post'),
    path('like/', views.like_unlike_post_view, name='like-unlike'),
    path('create/post/', views.create_post_view, name='create-post'),
    path('create/comment/', views.create_comment_view, name='create-comment'),

    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete-post'),
    path('update/<int:pk>/', views.UpdatePostView.as_view(), name='update-post'),
]

post/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

from account.models import Profile


class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='posts/', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(self.content[:20])

    class Meta:
        ordering = ('-created',)

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comments.all().count()

    def get_comments(self):
        return self.comments.all()


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


class Like(models.Model):
    LIKE = 'Like'
    UNLIKE = 'Unlike'

    VALUE_CHOICES = (
        (LIKE, 'Like'),
        (UNLIKE, 'Unlike'),
    )

    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='user_likes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_likes')
    value = models.CharField(choices=VALUE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

post/forms.py
from django import forms

from post.models import Post, Comment


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image')

        widgets = {
            'content': forms.Textarea(attrs={'rows': 3})
        }


class CreateCommentForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))

    class Meta:
        model = Comment
        fields = ('body',)

post/views.py
from django.contrib import messages

from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, DeleteView
from django.http import JsonResponse

from post.models import Post, Like
from account.models import Profile
from post.forms import CreatePostForm, CreateCommentForm


@login_required
def list_post_view(request):
    qs = Post.objects.all()
    profile = get_object_or_404(Profile, user=request.user)

    # Post form, Comment form
    p_form = CreatePostForm()
    c_form = CreateCommentForm()

    context = {
        'qs': qs,
        'profile': profile,
        'p_form': p_form,
        'c_form': c_form,
    }
    return render(request, 'post/main.html', context)


@login_required
@require_POST
def create_post_view(request):
    profile = get_object_or_404(Profile, user=request.user)
    p_form = CreatePostForm(data=request.POST or None, files=request.FILES or None)

    if p_form.is_valid():
        instance = p_form.save(commit=False)
        instance.author = profile
        instance.save()

    return redirect('post:list-post')


@login_required
@require_POST
def create_comment_view(request):
    post_id = request.POST.get('post_id')
    post = get_object_or_404(Post, id=post_id)

    profile = get_object_or_404(Profile, user=request.user)
    c_form = CreateCommentForm(data=request.POST or None)

    if c_form.is_valid():
        instance = c_form.save(commit=False)
        instance.user = profile
        instance.post = post
        instance.save()

    return redirect('post:list-post')


@login_required
@require_POST
def like_unlike_post_view(request):
    user_obj = request.user
    profile_obj = get_object_or_404(Profile, user=user_obj)

    post_id = request.POST.get('post_id')
    post_obj = get_object_or_404(Post, id=post_id)

    if profile_obj in post_obj.liked.all():
        post_obj.liked.remove(profile_obj)
    else:
        post_obj.liked.add(profile_obj)

    like, created = Like.objects.get_or_create(user=user_obj, post=post_obj)

    if created:
        like.value = Like.LIKE
    else:
        if like.value == Like.LIKE:
            like.value = Like.UNLIKE
        else:
            like.value = Like.LIKE
    
    profile_obj.save()
    like.save()

    return redirect('post:list-post')


class UpdatePostView(LoginRequiredMixin, UpdateView):
    template_name = 'post/update.html'
    model = Post
    form_class = CreatePostForm
    success_url = reverse_lazy('post:list-post')

    def get_object(self, queryset=None, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(Post, pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, message='You need to be the author of the post in order to update it.')
        return obj

    def form_valid(self, form):
        profile = get_object_or_404(Profile, user=self.request.user)

        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, 'You need to be the author of the post in order to update it.')
            return super().form_invalid(form)
 

class DeletePostView(LoginRequiredMixin, DeleteView):
    template_name = 'post/confirm_delete.html'
    model = Post
    success_url = reverse_lazy('post:list-post')

    def get_object(self, queryset=None, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(Post, pk=pk)

        if not obj.author.user == self.request.user:
            messages.warning(self.request, message='You need to be the author of the post in order to delete it.')
        return obj

templates/post/confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Post
{% endblock title %}

{% block content %}

    {% include 'post/partial/messages.html' %}

    {% if not messages %}
        <div class="ui segment">
            <h3>Delete post?</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete the post?</p>
                {{ obj.content }}
                <button type='submit'>Delete</button>
            </form>
        </div>
    {% endif %}

{% endblock content %}

templates/post/main.html
{% extends 'base.html' %}

{% block title %}Post{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in qs %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        <!-- Update and Delete -->
                        {% ifequal request.user obj.author.user %}
                            <a href="{% url 'post:update-post' obj.pk %}"><button class="ui button bwhite-lg">Update</button></a>
                            <a href="{% url 'post:delete-post' obj.pk %}"><button class="ui button bwhite-lg">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>
                    
                </div>
                <a href="{{ obj.author.get_absolute_url }}">
                    <img class="ui avatar image" src='{{ obj.author.avatar.url }}'> 
                </a>
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src='{{ obj.image.url }}'>
                {% endif %}
            </div>
            <div class="content">
                <!-- Show Content Post -->
                <p> {{ obj.content }} </p>
                <!-- Like-Unlike Form -->
                <div class="right floated">
                    <form action="{% url 'post:like-unlike' %}" method="POST" class='like-form' id='{{ obj.id }}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value='{{ obj.id }}'>
                        
                            <button type="submit" class="ui button like-btn{{obj.id}}">
                                {% if profile not in obj.liked.all %}
                                    Like
                                {% else %}
                                    Unlike
                                {% endif %}
                            </button>
                            <div class="ui grid">
                                <div class="column">
                                    <div class="like-count{{obj.id}}"> {{obj.num_likes}} </div>
                                </div>
                                <div class="column">
                                    likes
                                </div>
                            </div>
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <!-- Show Comment -->
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.get_comments %}
                    {% for comment in obj.get_comments %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src='{{ comment.user.avatar.url }}'>
                            <span>{{ comment.user.user }}</span>
                            <div class='mt-5'>{{ comment.body }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
                <!-- Create Comment Form -->
                <form action="{% url 'post:create-comment' %}" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{obj.id}}">
                    {{ c_form }}
                    <button type="submit" class="ui primary button mt-5 w-full">Comment</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <!-- Create Post Form -->
    <div class="five wide column">
        <div class="ui segment">
            <form action="{% url 'post:create-post' %}" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{ p_form }}
                <button type='submit' class="ui positive button w-full mt-5">Create</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });

            $('.like-form').submit(function(e){
                e.preventDefault()
                
                const post_id = $(this).attr('id')
                
                const likeText = $(`.like-btn${post_id}`).text()
                const trim = $.trim(likeText)

                const url = $(this).attr('action')
                
                let res;
                const likes = $(`.like-count${post_id}`).text()
                const trimCount = parseInt(likes)
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.like-count${post_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })

            })
        });
    </script>
{% endblock scripts %}

templates/post/update.html
{% extends 'base.html' %}

{% block title %}
    Update post
{% endblock title %}

{% block content %}

    {% include 'post/partial/messages.html' %}

    
    {% if not messages %}
        <div class='ui segment'>
            <h3>Update post</h3>
            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <button type='submit' class="ui button primary mt-5">Update</button>
            </form>
        </div>
    {% endif %}
        

{% endblock content %}