account/urls.py
from django.urls import path

from account import views

app_name = 'account'

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('update/', views.update_profile_view, name='update-profile'),
    path('profile/detail/<slug:slug>/', views.ProfileDetailView.as_view(), name='detail-profile'),

    path('invitations/received/', views.invitations_received_view, name='invitation-received-profile'),
    path('invitations/forward/', views.invitations_forward_view, name='invitation-forward-profile'),
    path('invitations/accept/', views.accept_invitation, name='invitation-accept'),
    path('invitations/reject/', views.reject_invitation, name='invitation-reject'),

    path('profiles/', views.ProfileListExcludeMeView.as_view(), name='profiles'),
    path('invitation/send/', views.send_invitation, name='invitation-send'),
    path('invitation/remove/', views.remove_from_friends, name='invitation-remove'),

    path('invitation/profiles/', views.invitation_profile_list_exclude_me_view, name='invitation-profiles'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


from config import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('post/', include('post.urls', namespace='post')),
    
    path('', views.home_view, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post import views

app_name = 'post'

urlpatterns = [
    path('', views.list_post_view, name='list-post'),
    path('like/', views.like_unlike_post_view, name='like-unlike'),
    path('create/post/', views.create_post_view, name='create-post'),
    path('create/comment/', views.create_comment_view, name='create-comment'),

    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete-post'),
    path('update/<int:pk>/', views.UpdatePostView.as_view(), name='update-post'),
]

templates/partial/navbar.html
{% url 'home' as path_to_home %}
{% url 'post:list-post' as path_to_post %}

{% url 'account:profile' as path_to_profile %}
{% url 'account:profiles' as path_to_profiles %}
{% url 'account:invitation-received-profile' as path_to_invitation_received_profile %}
{% url 'account:invitation-forward-profile' as path_to_invitation_forward_profile %}


<div class="ui inverted menu nav mb-7">
    <div class="ui container">
        <a href="{{ path_to_home }}" class="{% if request.path == path_to_home %}active{% endif %} item">
            <h3>Home</h3>
        </a>
        {% if request.user.is_authenticated %}
        <a href="{{ path_to_post }}" class="{% if request.path == path_to_post %}active{% endif %} item">
            Post
        </a>
        {% endif %}

        <div class="right menu">
            {% if request.user.is_authenticated %}
            <div class="item">
                <div class="ui floating dropdown icon button teal"> Friends
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <a href="{{ path_to_profiles }}" class="{% if request.path == path_to_profiles %}active{% endif %} item">
                            All Profiles
                        </a>
                        <a href="{{ path_to_invitation_forward_profile }}" class="{% if request.path == path_to_invitation_forward_profile %}active{% endif %} item">
                            Send Invites &nbsp; <div class="ui purple horizontal label">{{ invitations_forward_no }}</div>
                        </a>
                        <a href="{{ path_to_invitation_received_profile }}" class="{% if request.path == path_to_invitation_received_profile %}active{% endif %} item">
                            Received Invites &nbsp; <div class="ui purple horizontal label">{{ invitations_received_no }}</div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="item">
                <form action="" method="GET">
                    <div class="ui action left icon input">
                        <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                        <i class="search icon"></i>
                        <button type='submit' class="ui button">Search</button>
                    </div>
                </form>
            </div>

            <a href="{{ path_to_profile }}" class="{% if request.path == path_to_profile %}active{% endif %} item">
                <img src="{{ avatar.url }}" class="ui avatar image">&nbsp;
                {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>
            {% else %}
            <a href="{% url 'account_login' %}" class="ui item">
                Sign In
            </a>
            <a href="{% url 'account_signup' %}" class="ui item">
                Sign Up
            </a>
            {% endif %}
        </div>
    </div>
</div>